baseURL = "https://medvid.tk/"
languageCode = "en-us"
title = "Volodymyr Medvid | Blog"
theme = "hugo-xmin"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 3
[[menu.main]]
    name = "Notes"
    url = "/note/"
    weight = 4
[[menu.main]]
    name = "RSS"
    url = "/index.xml"

[params]
    footer = "&copy; [Volodymyr Medvid](https://medvid.tk) 2015-2017 | [Github](https://github.com/medvid) | [Facebook](https://www.facebook.com/vmmedvid)"
